runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /font-awesome
  static_dir: font-awesome

- url: /.*
  script: main.app
